-- Run plugin setup in dependency-safe order (after vim.pack.add).
return function()
  require('plugins.catppuccin').setup()
  require('plugins.treesitter').defer_bootstrap()
  require('plugins.snacks').setup()
  require('plugins.text-editing').setup()
  require('plugins.mason').setup()
  require('plugins.languages').setup()
  require('plugins.autocompletion').setup()
  require('plugins.fzf-lua').setup()
  require('plugins.lualine').setup()
  require('plugins.git').setup()
  require('plugins.lsp').setup()
  require('plugins.ui').setup()
  require('plugins.conform').setup()
  require('plugins.nvim-lint').setup()
  require('plugins.nvim-tree').setup()
  require('plugins.codex').setup()
  require('plugins.kitty').setup()
end
