" Define autocmd group vimrc.
augroup myvimrc
  autocmd!
augroup END

set rtp+=~/.vim/bundle/Vundle.vim

filetype off
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'tyrannicaltoucan/vim-deep-space'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'edkolev/tmuxline.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-dispatch'
Plugin 'airblade/vim-gitgutter'
Plugin 'kien/ctrlp.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'klen/python-mode'
Plugin 'ervandew/supertab'
Plugin 'scrooloose/nerdtree'
Plugin 'SirVer/ultisnips'
Plugin 'fatih/vim-go'
Plugin 'majutsushi/tagbar'

call vundle#end()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Plugins settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Vim-Tmux-Navigator
let g:tmux_navigator_no_mappings = 1

" Airline
let g:airline_theme = "deep_space"
let g:airline_powerline_fonts = 1

" Supertab
let g:SuperTabDefaultCompletionType = "<C-n>"

" UltiSnips
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<S-tab>"
let g:UltiSnipsSnippetDir="~/.vim/UltiSnips"

" Pymode
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_lint_unmodified = 1
let g:pymode_lint_checkers = ['pep8', 'pyflakes']


" vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_play_open_browser = 0
let g:go_dispatch_enabled = 1
let g:go_def_reuse_buffer = 0
autocmd myvimrc FileType go nnoremap <leader>g :GoDef<CR>
autocmd myvimrc FileType go nnoremap <F9> :GoTest<CR>
autocmd myvimrc FileType go nnoremap <F10> :GoRun<CR>

" CtrlP Settings
let g:ctrlp_max_height = 10
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_use_caching = 0
" configure CtrP to use git for autocompletion
if executable('ag')
    set grepprg=ag\ --nogroup\ --nocolor
    let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
else
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
    let g:ctrlp_prompt_mappings = {'AcceptSelection("e")': ['<cr>', '<2-LeftMouse>']}
endif

" Jedi-vim
let g:jedi#use_splits_not_buffers = "right"

"Disptach
autocmd myvimrc FileType python let b:dispatch = 'py.test -v %'
autocmd myvimrc FileType python nnoremap <F9> :Dispatch<CR>
autocmd myvimrc FileType python nnoremap <F10> :Dispatch python %<CR>

" NERDTree settings
map <F2> :NERDTreeToggle<CR>
let NERDTreeIgnore = ['\.pyc$', '\.egg-info$', '__pycache__']

" TagBar settings
map <F3> :TagbarToggle<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let mapleader = "\<Space>"
" Quickly edit dotfiles
nmap <silent> <leader>ev :vsplit $MYVIMRC<CR>
nmap <silent> <leader>et :vsplit ~/.tmux.conf<CR>
nmap <silent> <leader>ed :vsplit ~/.bash_profile<CR>
nmap <silent> <leader>r :so $MYVIMRC<CR>

" CLI/ GUI settings
if has("gui_running")
    " Start window maximized
    set lines=999 columns=999
    " Fix Powerline icons for the GUI
    set guifont=Inconsolata\ for\ Powerline:h14
else
    " Configure Vim to use 256 colours
    set t_Co=256
endif

" Vim, not vi
set nocompatible

" Show the command shortcut in the status line
set showcmd

" Optimize redrawing (improves speed)
set lazyredraw
set ttyfast

" Raise a dialogue for saving changes
set confirm

" Enable file type detection and plugin loading
filetype plugin indent on

" Use Unix as the standard file type
set ffs=unix,mac,dos

" Set output encoding
set encoding=utf-8

" Autoupdate file changes made outside vim
set autoread

" Set filetype specific options via modelines
set modeline

" Disable backups
set nobackup
set noswapfile
set nowritebackup

" Always display the status line, even if only one window is displayed
set laststatus=2

" Ignore these files
set wildignore+=*.pyc,*_build/*,*/coverage/*

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Colorscheme
try
    colors deep-space
catch
endtry

" Enable syntax highlighing
syntax enable

" Open splitpanes below and on the right of the current one.
set splitbelow
set splitright

" Toggle highlighting current line only in active splits
autocmd myvimrc VimEnter,WinEnter,BufWinEnter * setlocal cursorline
autocmd myvimrc WinLeave * setlocal nocursorline

" reload vimrc on save
autocmd myvimrc BufWritePost .vimrc,vimrc nested source $MYVIMRC

" Highlight current line
set cursorline

" Line numbers
set number
set relativenumber
map <F5> :set relativenumber!<CR>
map! <F5> <Esc>:set relativenumber!<CR>gi

" Regex and search options
set ignorecase
set smartcase
set hlsearch
set incsearch
set magic

" Temporary turn off hlsearch
nnoremap <silent> <leader><CR> :noh<CR>

" Save files
nmap <leader>w :w<CR>
vmap <leader>w <Esc>:w<CR>gv

" Close files (will raise confirmation dialog for unsaved changes)
nmap <leader>q :q<CR>
vmap <leader>q <Esc>:q<CR>gv

" Visual autocomplete for command menu
set wildmenu
" First tab will complete to the longest common string
set wildmode=longest:full,full

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Text and formatting
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Use 4 spaces instead of tabs
set tabstop=4
set shiftwidth=4
set expandtab

" Use 2 spaces instead of tabs for HTML and YAML files
autocmd myvimrc FileType html,yaml setlocal shiftwidth=2 tabstop=2

" Wrap lines to 72 characters in git commit messages and use 2 spaces for tab
autocmd myvimrc FileType gitcommit setlocal spell textwidth=72 shiftwidth=2 tabstop=2

" Don't leave space between joined lines
set nojoinspaces

" Fix identation when pasting in Insert mode
set pastetoggle=<F4>

" Sort lines alphabetically (useful for sorting Python imports)
vnoremap <leader>s :sort<CR>

" Go back to visual mode after reindenting
vnoremap < <gv
vnoremap > >gv

" Use double spacebar tab to select the current line
map <leader><leader> V

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Navigation and moving around
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Exit insert mode with jj
inoremap jj <Esc>

" Go to the next line in editor for wrapped lines
nnoremap j gj
nnoremap k gk

"Easier navigation through split windows
nnoremap <C-j> <C-w><Down>
nnoremap <C-k> <C-w><Up>
nnoremap <C-l> <C-w><Right>
nnoremap <C-h> <C-w><Left>

nnoremap <silent> <C-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <C-j> :TmuxNavigateDown<cr>
nnoremap <silent> <C-k> :TmuxNavigateUp<cr>
nnoremap <silent> <C-l> :TmuxNavigateRight<cr>
nnoremap <silent> <C-\> :TmuxNavigatePrevious<cr>

" We say 'NO' to arrow keys
nnoremap <Up> <NOP>
nnoremap <Down> <NOP>
nnoremap <Left> <NOP>
nnoremap <Right> <NOP>
inoremap <Up> <NOP>
inoremap <Down> <NOP>
inoremap <Left> <NOP>
inoremap <Right> <NOP>

" Useful mappings for managing tabs
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>tc :tabclose<cr>
map <leader>tm :tabmove

" Remap 0 to go to first non-blank character of the line
map 0 ^

" Remap Y to apply till EOL, just like D and C.
map Y y$
