typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt|f3'
typeset -g POWERLEVEL9K_AWS_CLASSES=(
  '*'       DEFAULT)
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=$black
typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}${P9K_AWS_REGION:+ ${P9K_AWS_REGION//\%/%%}}'
