typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=$aqua
typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=$grey
typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=false
typeset -g POWERLEVEL9K_GO_VERSION_VISUAL_IDENTIFIER_EXPANSION='ﳑ'
typeset -g POWERLEVEL9K_GO_VERSION_SHOW_ON_COMMAND='go'
