typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=$olive
typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=$black
typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=false
typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false
typeset -g POWERLEVEL9K_JAVA_VERSION_SHOW_ON_COMMAND='java|javac|gradle|gradlew'
