typeset -g POWERLEVEL9K_LOAD_WHICH=1
typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=$lime
typeset -g POWERLEVEL9K_LOAD_NORMAL_BACKGROUND=$black
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=$yellow
typeset -g POWERLEVEL9K_LOAD_WARNING_BACKGROUND=$black
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=$red
typeset -g POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND=$black
typeset -g POWERLEVEL9K_LOAD_VISUAL_IDENTIFIER_EXPANSION='󰄨 '
