typeset -g POWERLEVEL9K_LOAD_WHICH=1
typeset -g POWERLEVEL9K_LOAD_NORMAL_FOREGROUND=$grey
typeset -g POWERLEVEL9K_LOAD_NORMAL_BACKGROUND=$lime
typeset -g POWERLEVEL9K_LOAD_WARNING_FOREGROUND=$grey
typeset -g POWERLEVEL9K_LOAD_WARNING_BACKGROUND=$yellow
typeset -g POWERLEVEL9K_LOAD_CRITICAL_FOREGROUND=$grey
typeset -g POWERLEVEL9K_LOAD_CRITICAL_BACKGROUND=$red
