typeset -g POWERLEVEL9K_TIME_FOREGROUND=$white
typeset -g POWERLEVEL9K_TIME_BACKGROUND=$black
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=
