# vim: foldmethod=marker
# Oh-My-Zsh {{{1

export ZSH="${HOME}/.oh-my-zsh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
    aws
    colored-man-pages
    docker
    F-Sy-H
    git
    golang
    helm
    httpie
    kubectl
    npm
    terraform
    tmux
    vi-mode
    you-should-use
    z
    zsh-autosuggestions
    zsh-nvm
    fzf-tab # fzf-tab should be the last plugin to bind "^I"
)

# Settings that must be applid before loading Oh-My-Zsh {{{2

# Set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Use case-sensitive completion
CASE_SENSITIVE="true"

# Fix slow paste
DISABLE_MAGIC_FUNCTIONS=true

# Enable Node Version Manager lazy load
export NVM_LAZY_LOAD=true
export NVM_LAZY_LOAD_EXTRA_COMMANDS=('vim')

# Workaround for https://github.com/zsh-users/zsh-completions/issues/603
if [[ -d "${ZSH_CUSTOM}/plugins/zsh-completions/src" ]]; then
  fpath+="${ZSH_CUSTOM}/plugins/zsh-completions/src"
fi

# }}}

# Load oh-my-zsh
source "${ZSH}/oh-my-zsh.sh"

# ZSH {{{1

# Apply sensisble zsh settings
source ~/dotfiles/zsh/zshopt

# Bind C+Space to accept the current suggestion
bindkey '^ ' autosuggest-accept

# Set the default umask
umask 022

# OSTYPE specific settings
case "${OSTYPE}" in
    linux*)
        if (( $+commands[setxkbmap] )); then
            setxkbmap -option caps:escape_shifted_capslock
            setxkbmap -option altwin:swap_lalt_lwin
        fi
        ;;
    *) ;;
esac

# Source files {{{2
# Load aliases
source ~/dotfiles/zsh/aliases.zsh

# Apply FZF configuration
source ~/dotfiles/zsh/fzf.zsh

# Load any extra settings
test -f ~/dotfiles/zsh/extras && source ~/dotfiles/zsh/extras

# Completion {{{2

# set descriptions format to enable group support
zstyle ':completion:*:descriptions' format '[%d]'

# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false

# Only display targets tag for make command completion
zstyle ':completion:*:*:make::' tag-order 'targets variables'

# give a preview of commandline arguments when completing `kill`
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm -w -w"

# Other {{{2

# disable highlighting of pasted text
zle_highlight=('paste:none')

# Reload the completions (uncomment if zsh-completions don't work)
# autoload -U compinit && compinit
