# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/georgi/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="oxide"

# Update the list of identities so the ssh-agent plugin sets up the correct ones
zstyle :omz:plugins:ssh-agent identities id_rsa hf_id_rsa

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    docker
    git
    golang
    kubectl
    npm
    nvm
    ssh-agent
    tmux
    vi-mode
    web-search
    z
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second)
export KEYTIMEOUT=1

# Fix Ctrl+<key>
stty -ixon

# Set keyboard settings
setxkbmap -layout us,bg -variant ,phonetic -option ctrl:nocaps grp:ctrl_alt_toggle

# Set the default umask
umask 022

# Resolve symbolic links to their true values when changing directory
setopt CHASE_LINKS

unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1

export PATH=$PATH:$HOME:.
export EDITOR=vim
export XDG_CONFIG_HOME=~/.config
export REPOS=/repos

# Golang
export GOPATH=$REPOS/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

case "$OSTYPE" in
    darwin*)
        LS_OPTS="-G"
        ;;
    linux*)
        LS_OPTS="--color=auto --group-directories-first"
        ;;
    *) ;;
esac

if [ "$DESKTOP_SESSION" = "i3" ]; then
    export $(gnome-keyring-daemon --start)
    # SSH_AGENT_PID required to stop xinitrc-common from starting ssh-agent
    export SSH_AGENT_PID="${GNOME_KEYRING_PID:-gnome}"
fi

set editing-mode vi
set blink-matching-paren on

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/dotfiles/zsh/aliases
test -f ~/dotfiles/zsh/extras && source ~/dotfiles/zsh/extras

# vi-mode extras
# allow arrow keys to search history in insert mode
bindkey "^[OA" up-line-or-beginning-search
bindkey "^[OB" down-line-or-beginning-search
# allow home keys to search history in normal mode
bindkey -M vicmd "k" up-line-or-beginning-search
bindkey -M vicmd "j" down-line-or-beginning-search
