#!/bin/bash
# vim: set filetype=sh:

function extract () {
    if [ -f $1 ]; then
        case $1 in
            *.tar.bz2)   tar xjf $1     ;;
            *.tar.gz)    tar xzf $1     ;;
            *.bz2)       bunzip2 $1     ;;
            *.rar)       unrar e $1     ;;
            *.gz)        gunzip $1      ;;
            *.tar)       tar xf $1      ;;
            *.tbz2)      tar xjf $1     ;;
            *.tgz)       tar xzf $1     ;;
            *.zip)       unzip $1       ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1        ;;
            *)     echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# misc
alias ls='ls $LS_OPTS'
alias ll='ls -lh'
alias la='ls -lah'
alias lt='ls -ltrh'
alias grep='grep --color=auto'
alias grepi='grep -i'
alias vim='vim -O'

# docker
function dps() {
    docker ps "$@" --format \
        'table {{.ID}}\t{{.Image}}\t{{.Command}}\t{{.RunningFor}}\t{{.Status}}\t{{.Names}}' \
        | sed -re 's|([0-9a-f]+\s+)containers.*:[0-9]{4}/|\1cbnnn/|' \
        -e 's|  +|\t|g' \
        | column -ts "$(echo -e "\t")"
}
alias dpsa='dps -a'
alias drm='docker rm -fv `docker ps -qa`'
alias dvrm='docker volume rm `docker volume ls -q`'

# git
alias gc='git commit'
alias gca='git commit --amend'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch --all'
alias gp='git push'
alias gpp='git pull'
alias gs='git status --u=all'
alias ggrep='git grep -B0 -A0'
alias ggrepi='ggrep --ignore-case'
alias gu='git stash && git pull && git stash pop || true'

# tmux
alias tmux='tmux -2'
alias ta='tmux attach -t'
alias tk='tmux kill-session -t'
