# vim: set filetype=sh:

# If not running interactively, don't do anything
case $- in
    *i*) ;;
    *) return;;
esac

# History file settings
HISTCONTROL=erasedups:ignoreboth
HISTFILESIZE=500000
HISTSIZE=100000
HISTTIMEFORMAT='%F %T '
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"
shopt -s histappend

# update the screen after every command
shopt -s checkwinsize

# Fix Ctrl+<key>
stty -ixon

# Exports
export CLICOLOR=1
export EDITOR=vim
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$HOME:.
export REPOS=/repos
# Golang
export GOPATH=~/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

case "$OSTYPE" in
    darwin*)
        if [ -f $(brew --prefix)/etc/bash_completion ]; then
            . $(brew --prefix)/etc/bash_completion
        fi
        LS_OPTS='-G'
        ;;
    linux*)
        if ! shopt -oq posix ; then
          if [ -f /usr/share/bash-completion/bash_completion ]; then
            . /usr/share/bash-completion/bash_completion
          elif [ -f /etc/bash_completion ]; then
            . /etc/bash_completion
          fi
        fi
        LS_OPTS='--color=auto --group-directories-first'
        ;;
    *) ;;
esac

test -f /etc/bash_completion.d/docker && . /etc/bash_completion.d/docker 
test -f ~/.bash_aliases && . ~/.bash_aliases
test -f ~/.git-completion.sh && . ~/.git-completion.sh

if [ "$DESKTOP_SESSION" = "i3" ]; then
    export $(gnome-keyring-daemon --start)
    # SSH_AGENT_PID required to stop xinitrc-common from starting ssh-agent
    export SSH_AGENT_PID=${GNOME_KEYRING_PID:-gnome}
fi

# Prompt

# Automatically trin long paths in the prompt
PROMPT_DIRTRIM=2

set -o vi

test -f ~/.git-prompt.sh && . ~/.git-prompt.sh
test -f ~/.colors && . ~/.colors

function prompt_before() {
    local result=$?
    local hostname=$(test -z "$TMUX" && echo "$BYELLOW[\h]")
    local virtenv=$(test $VIRTUAL_ENV && echo "$BCYAN[$(echo $VIRTUAL_ENV|rev|cut -d"/" -f1,2|rev)]")
    local curdir="$BPURPLE[\w]"
    echo "${hostname}${virtenv}${curdir}$OFF"
    return $result
}

function prompt_after() {
    local color=$([ $? = 0 ] && echo "$BGREEN" || echo "$BRED")
    echo "\n${color}\$$OFF "
}

GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_DESCRIBE_STYLE="branch"
GIT_PS1_SHOWUPSTREAM="auto git"

PROMPT_COMMAND='__git_ps1 "$(prompt_before)" "$(prompt_after)" "[%s]"'
