name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
        env:
          UBUNTU_VERSION: '${{ matrix.os }}'
